### ISSUE TITLE
Word lists not working

### ISSUE THREAD

**Issue by CaptainOfTheSky** [cwackerfuss/word-guessing-game#111]
They word lists aren't working  (I cloned this today)

I've updated my wordlist and validGuesses with custom words, and they aren't taking effect. A normal word that is NOT in my list is going through, and a valid word in my list is saying 'word not found'.

**Comment by cwackerfuss** [comment]
I'm not sure what the issue is with your clone -- can you share a github repo where I can look at the code?

**Comment by MohammedAlrozzi** [comment]
I had this issue because I cleared all the words in the ValidGuess. Try to add just one word to that list and it should work.

**Comment by CaptainOfTheSky** [comment]
the issue was due to the wordlist being case sensitive. Its alright if you're sure you're typing everything lower case, but I changed the isInWordList to the following. It could probably be cleaner but it works

`export const isWordInWordList = (word: string) => {

  const inWords = WORDS.findIndex(element => {
    return element.toLowerCase() === word.toLowerCase();
  });
  const inGuesses = VALIDGUESSES.findIndex(element => {
    return element.toLowerCase() === word.toLowerCase();
  });
  return (
    inWords > -1 || inGuesses > -1
  )
}
`
