### ISSUE TITLE
Make the number of letters per word configurable ...

### ISSUE THREAD

**Issue by kedarmhaswade** [cwackerfuss/word-guessing-game#117]
First off, this is great work! Factoring things out requires a keen insight. Thank you!

I am trying to port the game to a different language.

Is there a way to make changes to the number of letters in a word? It seems that that the number of letters in a word is fixed at 5? What all changes would be needed to make the length 3 or 4 or anything else?

**Comment by cwackerfuss** [comment]
Hey @kedarmhaswade !! This is a great question and one I feel like others have had before as well. I just added a section to the readme to answer this: https://github.com/cwackerfuss/word-guessing-game#how-can-i-change-the-length-of-a-guess

**Comment by kedarmhaswade** [comment]
Thank you, @cwackerfuss!
