### ISSUE TITLE
My advice for a language with multiple length unicode characters

### ISSUE THREAD

**Issue by trosel** [cwackerfuss/word-guessing-game#87]
Firstly, thank you @hannahcode! I made a fork for Shavian. [Repo](https://github.com/trosel/shawdle/) and [app](https://shavian.school/shawdle/shawdle.html) (I am just hosting the app on github pages using the build directory).

I added the package `grapheme-splitter` to the app.

Then you can see how I handled adding new unicode letters and splitting them in these two commits:

1. https://github.com/trosel/shawdle/commit/076dba495344885230b2a9cf73f5a398e00a92ca
2. https://github.com/trosel/shawdle/commit/50dece60c4dcdb5c277f935a4bd04aca7e06e57b

**Comment by jacbrixey** [comment]
This was really good advice! Thanks for sharing, it really helped me

**Comment by trosel** [comment]
Hmm. So you can use grapheme-splitter to ensure that you get a normal length every time (even if it just 5 ASCII characters). 

But you still may have a problem of the length of the Cells where the letters go.

Perhaps you can change the logic in some of these functions. https://github.com/trosel/shawdle/commit/076dba495344885230b2a9cf73f5a398e00a92ca#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2

instead of “guess.length === 5” (i changed it to 10) , you could say “splitter.split(guess).length === 5”. So you’re counting the length of the grapheme array instead.

**Comment by jacbrixey** [comment]
@trosel  Your suggestion for adding the splitter on the currentGuess.length worked like a charm!
