### ISSUE TITLE
Unclear future of this project

### ISSUE THREAD

**Issue by hannahcode** [cwackerfuss/word-guessing-game#90]
Hi everyone, I never anticipated this project would grow so large, nor that a key source of its inspiration would be acquired by NYT. For these reasons I'm not sure I want to hold and maintain it. I'm open to suggestions, just wanted to be honest and start this conversation. If you are a  contributor who would be comfortable owning this project please let me know.

**Comment by Geczy** [comment]
I would be comfortable owning this project for you :)

**Comment by pumbinha** [comment]
Hi @hannahcode ,

I just want to say that you've been doing a great job, congratulations for it.

But in the end, is your project, you created it from scratch, and that deserves recognition!

Maybe you can feel more comfortable naming some people that help you with it. I understand that checking and taking care of the PR's alone can be too much (not me, I'm still learning react and I'm a beginner).

Just my opinion :)

**Comment by hannahcode** [comment]
Thanks! That might be a good idea. @gbear605, @jnsturgis, and @eggplants as top contributors I would love to know your thoughts.

**Comment by jnsturgis** [comment]
Hi @hannahcode

I fully agree with @pumbinha it is your project even if others have contributed you have been doing the management job and had the ideas and created from scratch - congratulations go to you. I am of course happy to be part of the project, but as a complete novice in React, Typescript and Tailwind clearly do not have the credentials to be anything other than a minor participant. It really showed when you refactored my code that you know what you are doing (and I do not) ;-) . Happy to help in any way I can.

**Comment by dharmeshs** [comment]
Thank you for bringing this project as far along as you have. I'm using it for a fun, nights/weekends project to learn (and add some features I want for myself).  

Cheers.

**Comment by cwackerfuss** [comment]
Hi folks! Just wanted to introduce myself -- @hannahcode asked me to jump in and help maintain this project while she takes a break and continues hunting for a job. I want to thank everyone for the kind words of motivation. This is a new experience for both of us so we're taking it one pull request at a time! We're both honored the community has come together and helped out so much with this project.

It seems like every other day now that I'll see a new "word-guessing-game" clone out in the wild. My favorite so far is https://www.taylordle.com/ 👯

**Comment by igitur** [comment]
So my derivative implementation, [Wortel](https://wortel.wrintiewaar.co.za), has been quite a hit and I've been getting some media queries. I can't really take much credit for it. It was a breeze to set up initially and the translation instructions in `README.md` was extremely clear. I had a translated version up 'n running on an Azure instance within an hour. 

@hannahcode, you did a fantastic job with this project. I'd love to credit you in my media responses, but not without your permission. If you're OK with me mentioning you as the original author, please let me know (either here or via Gmail; same username). Else I'll just say that I based my implementation on open-source work of others. 

And I know that there have been other contributors, but let's be honest: Hannah did the bulk of the initial work.
