### ISSUE TITLE
Missing the Code of Conduct and Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [cwackerfuss/word-guessing-game#91]
The project is missing the ISSUE TEMPLATES and a Code of Conduct. If you want to add them, then I would want to submit a PR with those.

Please let me know what do you think about that, and one more thing, this project is really the representation of your amazing work. Please don't think of changing the ownership to anyone else. You can obviously add more contributors or maintainers, but please do not change the ownership.

**Comment by cwackerfuss** [comment]
Hey @FahimFBA ! Appreciate the kind words to @hannahcode, she asked me to help her maintain this project so I think she took you and the communities words to heart :)

We'd be happy to approve a PR that adds an issues template and code of conduct. Feel free to ask any questions that may come up on this issue

**Comment by FahimFBA** [comment]
I am glad that she feels that way. 😀As an open-source contributor for a long time, I can understand how important a project can be to the project owner because he/she needs to spend a lot of time and provide a lot of care for maintaining that as well. Also, we all respect the project owner, maintainers and all the contributors. 


About the Code of Conduct, I need an email address that would go with the Code of Conduct. 😊

**Comment by cwackerfuss** [comment]
@FahimFBA ah, thanks! I realized its pretty simple to add these, just did it. 👍
